apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-num-toots-by-date
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: get_num_toots_by_date.main
    packageref:
      name: mastodon-real-time
      namespace: ""
  requestsPerPod: 1
  resources: {}
  secrets:
  - name: secrets
    namespace: ""
