include:
- backend/bom_real_time/bom_real_time.zip
kind: ArchiveUploadSpec
name: backend-bom-real-time-bom-real-time-zip-ZOZV

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bom-real-time
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-bom-real-time-bom-real-time-zip-ZOZV
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-18T05:03:02Z"
