include:
- A2.zip
kind: ArchiveUploadSpec
name: a2-zip-TX4S

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: a2
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://a2-zip-TX4S
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-04T07:17:27Z"
