include:
- backend/bom_past_rainfall/bom-past-rainfall.zip
kind: ArchiveUploadSpec
name: backend-bom-past-rainfall-bom-past-rainfall-zip-rIQ2

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bom-past-rainfall
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-bom-past-rainfall-bom-past-rainfall-zip-rIQ2
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-18T07:37:43Z"
