include:
- get_bom_mastodon_by_date/get_bom_mastodon_by_date.zip
kind: ArchiveUploadSpec
name: get-bom-mastodon-by-date-get-bom-mastodon-by-date-zip-SmEu

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-bom-mastodon-by-date
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://get-bom-mastodon-by-date-get-bom-mastodon-by-date-zip-SmEu
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-18T05:23:21Z"
