include:
- ./backend/bom_mastodon/get_bom_mastodon_by_date.zip
kind: ArchiveUploadSpec
name: backend-bom-mastodon-get-bom-mastodon-by-date-zip-bxGK

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-bom-mastodon-by-date
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-bom-mastodon-get-bom-mastodon-by-date-zip-bxGK
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-18T06:14:48Z"
