include:
- ./backend/health_geo/health.zip
kind: ArchiveUploadSpec
name: backend-health-geo-health-zip-ECxD

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: health
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-health-geo-health-zip-ECxD
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T12:03:57Z"
