apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-health
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-health
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /health/get-health
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /health/get-health
