apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-rainfall
spec:
  createingress: false
  functionref:
    functionweights: null
    name: rainfall
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /bom-past-rainfall/rainfall/{date}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /bom-past-rainfall/rainfall/{date}
