apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: air-quality-avg
spec:
  createingress: false
  functionref:
    functionweights: null
    name: air-quality-avg
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /air-quality/air-quality-avg/{location}/{date}/{days}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /air-quality/air-quality-avg/{location}/{date}/{days}
