apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-bom-mastodon-by-date
spec:
  createingress: true
  functionref:
    functionweights: null
    name: get-bom-mastodon-by-date
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /bom-mastodon/{date}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /bom-mastodon/{date}
